name: Build and Push Docker Image

on:
  push:
    branches:
    - main
  schedule:
  - cron: '0 0 * * 0'  # This will run every Sunday at midnight

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.21'
    - uses: ko-build/setup-ko@v0.6
    - run: ko build --bare
